spring:
  application:
    name: CuRestDev

server:
  port: 8083

spring:
  datasource:
    url: jdbc:db2://10.10.52.131:55000/equivida
    username: usuario
    password: user_desa
    driver-class-name: com.ibm.db2.jcc.DB2Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    
server:
  servlet:
    context-path: /cu-rest

management:
  endpoints:
    web:
      exposure:
        include: '*'
