spring:
  application:
    name: CuRestDev
  datasource:
    url: jdbc:db2://10.10.52.131:55000/equivida   

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: '*'
